# Generated by Django 5.0.3 on 2024-04-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Pro', 'Pro')])),
                ('un_dia', models.PositiveIntegerField()),
                ('dos_a_tres', models.PositiveIntegerField()),
                ('cuatro_a_seis', models.PositiveIntegerField()),
                ('siete_o_mas', models.PositiveIntegerField()),
                ('hora_extra', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='imagenes_autos')),
                ('puertas', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('pasajeros', models.PositiveSmallIntegerField()),
                ('baul', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
                ('caja', models.CharField(choices=[('Automatica', 'Automatica'), ('Manual', 'Manual')])),
                ('disponible', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('devuelto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.cliente')),
            ],
        ),
    ]
