# Generated by Django 5.0.3 on 2024-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_plan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trimestre',
            field=models.CharField(choices=[('Marzo/Abril/Mayo', 'Marzo/Abril/Mayo'), ('Junio/Julio/Agosto', 'Junio/Julio/Agosto'), ('Septiembre/Octubre/Noviembre', 'Septiembre/Octubre/Noviembre'), ('Diciembre/Enero/Febrero', 'Diciembre/Enero/Febrero')], default=1),
            preserve_default=False,
        ),
    ]
