# Generated by Django 5.0.3 on 2024-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_plan_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cuatro_a_seis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dos_a_tres',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hora_extra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='siete_o_mas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='un_dia',
            field=models.FloatField(),
        ),
    ]
