# Generated by Django 5.0.3 on 2024-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_plan_cuatro_a_seis_alter_plan_dos_a_tres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cuatro_a_seis',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dos_a_tres',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hora_extra',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='siete_o_mas',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='un_dia',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
    ]
