# Generated by Django 5.0.3 on 2024-04-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_plan_cuatro_a_seis_alter_plan_dos_a_tres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='plan',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Pro', 'Pro')]),
        ),
    ]
