# Generated by Django 5.0.3 on 2024-04-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_remove_rental_cliente_rental_apellido_rental_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
