# Generated by Django 5.0.3 on 2024-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_alter_rental_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
