# Generated by Django 5.0.3 on 2024-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rental_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
