# Generated by Django 5.0.3 on 2024-04-09 12:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_rental_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='color',
            field=colorfield.fields.ColorField(default='#89CFF0', image_field=None, max_length=25, samples=None),
        ),
    ]
