# Generated by Django 5.0.4 on 2024-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_alter_rental_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cuatro_a_seis',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dos_a_tres',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='siete_o_mas',
        ),
        migrations.AlterField(
            model_name='plan',
            name='tipo',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Estandar', 'Estandar'), ('Pro', 'Pro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trimestre',
            field=models.CharField(choices=[('Marzo/Abril/Mayo', 'Marzo/Abril/Mayo'), ('Junio/Julio/Agosto', 'Junio/Julio/Agosto'), ('Septiembre/Octubre/Noviembre', 'Septiembre/Octubre/Noviembre'), ('Diciembre/Enero/Febrero', 'Diciembre/Enero/Febrero')], max_length=50),
        ),
    ]
