# Generated by Django 5.0.4 on 2024-05-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_remove_plan_cuatro_a_seis_remove_plan_dos_a_tres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='abril',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='agosto',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='diciembre',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='febrero',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='julio',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='junio',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='marzo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='mayo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='noviembre',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='octubre',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='septiembre',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
