# Generated by Django 5.0.4 on 2024-05-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_plan_abril_plan_agosto_plan_diciembre_plan_febrero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='un_dia',
            new_name='enero',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='trimestre',
        ),
    ]
