# Generated by Django 5.0.4 on 2024-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0016_rename_un_dia_plan_enero_remove_plan_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
