# Generated by Django 5.0.4 on 2024-05-03 06:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_alter_rental_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#89CFF0', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
