# Generated by Django 5.0.3 on 2024-05-31 19:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_alter_rental_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#89CFF0', image_field=None, max_length=25, null=True, samples=[('#549ccc', 'azul'), ('#59af80', 'verde'), ('#de583d', 'naranja'), ('#aa61bb', 'violeta')]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='fecha_retiro',
            field=models.DateTimeField(),
        ),
    ]
