# Generated by Django 5.0.3 on 2024-06-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_alter_rental_color_alter_rental_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.DecimalField(decimal_places=3, max_digits=50)),
            ],
        ),
    ]
