# Generated by Django 5.0.3 on 2024-06-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_seguro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguro',
            old_name='full',
            new_name='precio',
        ),
    ]
