# Generated by Django 5.0.3 on 2024-06-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_seguro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='seguro_full',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True),
        ),
    ]
